### ISSUE TITLE
windows窗口隐藏

### ISSUE THREAD

**Issue by LordCasser** [INotGreen/XiebroC2#10]
我知道如何做windows的窗口隐藏和如何用go写payload来过免杀，我有一套自己的框架，但是前端写的比较烂
我需要控制端源码来参考一下，或许可以直接把我的payload程序支持你们的控制端

**Comment by badboycxcc** [comment]
为什么需要控制端源码？不是直接对被控端进行处理吗？

**Comment by badboycxcc** [comment]
执行被控端会有个一闪而过的黑框

**Comment by INotGreen** [comment]
其实这样隐藏控制台会被360QVM杀了，如果把那串隐藏控制台的代码删了应该就能免杀了

**Comment by LordCasser** [comment]
> 为什么需要控制端源码？不是直接对被控端进行处理吗？

我在跟作者对话，不是你

[录屏 2024年02月19日 11时30分58秒.webm](https://github.com/INotGreen/XiebroC2/assets/35390821/a7e9aa62-9c35-4c4b-8326-9c4639635a51)

**Comment by INotGreen** [comment]
没看出问题出在哪里

**Comment by INotGreen** [comment]
控制端我下个版本会发布一版可以破解的，不发Controler源码还是怕有些小黑拿来乱改然后去卖控

**Comment by badboycxcc** [comment]
> > 为什么需要控制端源码？不是直接对被控端进行处理吗？
> 
> 我在跟作者对话，不是你
> 
>  2024.02.19.11.30.58.webm

非常抱歉。

**Comment by LordCasser** [comment]
> 控制端我下个版本会发布一版可以破解的，不发Controler源码还是怕有些小黑拿来乱改然后去卖控

我也有一整套，但是Controler前端交互设计的比较烂，打算重构
![image](https://github.com/INotGreen/XiebroC2/assets/35390821/839de249-ad20-42e3-bae0-a3cf27475ceb)
看你信不信的过

**Comment by INotGreen** [comment]
你可以加我微信，后面在聊，这几天在忙
