### ISSUE TITLE
Problem with TeamServer on Windows 10

### ISSUE THREAD

**Issue by matmad** [INotGreen/XiebroC2#14]
I have downloaded the pre-compiled version of the software and when trying to start teamserver on windows 10 machine I get the errors from screenshot. Any idea what should I do? 
![Untitled-1](https://github.com/INotGreen/XiebroC2/assets/13328083/f082390f-71f5-46dc-8cac-801c443d9810)

**Comment by INotGreen** [comment]
Change the TeamserverIP in profile1.json to your own IP, then 
`Teamserver.exe -c profile1.json`

**Comment by matmad** [comment]
Thank you!
