### ISSUE TITLE
GLIBC_2.34' not found

### ISSUE THREAD

**Issue by pingpongcult** [INotGreen/XiebroC2#17]
root@kali:~/xiebro# ./TeamServer -C profile1.json 
./TeamServer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./TeamServer)

![image](https://github.com/INotGreen/XiebroC2/assets/18239811/c836c1c7-89ee-4c82-9809-19a1e86fed18)

**Comment by pingpongcult** [comment]
![image](https://github.com/INotGreen/XiebroC2/assets/18239811/3c5c3f4b-907a-49db-b8af-59cd945da118)

**Comment by INotGreen** [comment]
Try to upgrade the operating system version to Debian10+
