### ISSUE TITLE
cdn域名上线是监听器选择Windows/Session/Reverse_Ws，然后host处填写域名，port处填写cdn可使用的端口就行了吗？这样并没能成功上线。

### ISSUE THREAD

**Issue by tony79857** [INotGreen/XiebroC2#21]

**Comment by INotGreen** [comment]
我测试的是80端口，cf可以上线

**Comment by INotGreen** [comment]
有些云服务厂商的websocket是需要额外计费的，例如：[阿里云Websocket服务](https://help.aliyun.com/zh/dcdn/configure-websocket)

**Comment by INotGreen** [comment]
![image](https://github.com/INotGreen/XiebroC2/assets/89376703/2e50193a-10f8-45ac-8ded-c4bb6d9b7a19)

我这里上线测试是成功了，之前的版本确实有点小bug，用国内的某里云，发现Cloud flare被拦截了，应该是CF被滥用了，修复的版本已经发在release上了

**Comment by n0n5m1l3** [comment]
using the new release you stated above and getting the below error and unable to build payloads
![build-error](https://github.com/INotGreen/XiebroC2/assets/28440950/a1286ab5-09eb-4128-a53a-de2262b174b6)

![image](https://github.com/INotGreen/XiebroC2/assets/28440950/6a613e2e-2ab7-44f2-ae12-8672db530b7d)

**Comment by INotGreen** [comment]
> 使用您上面提到的新版本并收到以下错误并且无法构建有效负载 ![构建错误](https://private-user-images.githubusercontent.com/28440950/313149652-a1286ab5-09eb-4128-a53a-de2262b174b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTY5NTcsIm5iZiI6MTcxMDU5NjY1NywicGF0aCI6Ii8yODQ0MDk1MC8zMTMxNDk2NTItYTEyODZhYjUtMDllYi00MTI4LWE1M2EtZGUyMjYyYjE3NGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDEzNDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OTdkMzlhZWExMjU5YzEzNTkyODgwNWQzNjA5MGNlNzFkYWJjMTkyODY0ZmI5ZTY3M2MyMjU4M2I2NjAwYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GK4kqLB2n7gq8HZgW2veebqMwXKEHsHyshuKlaDJwX0)
> 
> ![图像](https://private-user-images.githubusercontent.com/28440950/313150458-6a613e2e-2ab7-44f2-ae12-8672db530b7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTY5NTcsIm5iZiI6MTcxMDU5NjY1NywicGF0aCI6Ii8yODQ0MDk1MC8zMTMxNTA0NTgtNmE2MTNlMmUtMmFiNy00NGYyLWFlMTItODY3MmRiNTMwYjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDEzNDQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MWE4YTBiMjNkYTBhOTEwZWFjZTY3ZDk5MmM3NDYyZTI4MjI3MmZkYjhhNTA4M2ZlMmNjOWNiZDMwYzA0ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1IV8gTklJisSLWXq5wE8ubAjzeakeLeX7EZxCucQgY)

This is a bug. The cdn domain name length of the controlled end is limited. I will fix it in the next version recently, but you can still compile the new controlled end by compiling Go code.
