### ISSUE TITLE
反向代理无效

### ISSUE THREAD

**Issue by simlelcf** [INotGreen/XiebroC2#23]
开启反向代理
![image](https://github.com/INotGreen/XiebroC2/assets/18651522/51554afb-d922-4a32-86b8-6dd63924d45a)

./teamServer 并没有开启s5和监听端口
![image](https://github.com/INotGreen/XiebroC2/assets/18651522/8328d738-2c32-430d-986e-08303b2fba25)

**Comment by simlelcf** [comment]
只是打印截图错误，两个端口是不一样的
![image](https://github.com/INotGreen/XiebroC2/assets/18651522/fa8ce306-f5f0-4cff-ba01-438e20f853f5)

**Comment by INotGreen** [comment]
可以重启一下在试试

**Comment by simlelcf** [comment]
还是一样，TeamServer 重启 开启反向代理，Teamserver 服务器还是没有开启监听和S5端口，Teamserver 是ubuntu 20

**Comment by INotGreen** [comment]
反向代理已经修复
