### ISSUE TITLE
反向代理失败

### ISSUE THREAD

**Issue by Xiaozes** [INotGreen/XiebroC2#27]
我也遇到了 那位师傅的问题 ，socks代理无效，设置了同样的端口 ，但是不能进行socks代理
我的环境是 server / client 都是ubuntu
进行socks 代理实效 ，请问您的socks代理是否只在windows 上进行了 测试，没有对linux 进行兼容
希望您能在 下一个版本解决这个问题 ，万分感谢

**Comment by INotGreen** [comment]
反向代理那个问题修复了，你可以再次尝试新版本
