### ISSUE TITLE
BUG An attempt was made to load a program with an incorrect format. Plugins

### ISSUE THREAD

**Issue by LeetIDA** [INotGreen/XiebroC2#34]
error:An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

![image](https://github.com/user-attachments/assets/a3e9eecf-05fa-4618-8525-557b0596fd7e)

**Comment by INotGreen** [comment]
You need to update all versions ，https://github.com/INotGreen/XiebroC2/releases，and plugins to the latest version.：https://github.com/INotGreen/Xiebro-Plugins

**Comment by LeetIDA** [comment]
latest version not working for me when i connect nothing happen

**Comment by INotGreen** [comment]
You need to read the documentation carefully，https://github.com/INotGreen/XiebroC2/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B

**Comment by king-of-bypass** [comment]
error:Cannot invoke delegate (invalid arguments for AddMenultemB)
![微信截图_20240829202013](https://github.com/user-attachments/assets/b1950a94-4f21-4276-8dac-69396b493141)
![Uploading 微信图片_20240829202201.png…]()

**Comment by king-of-bypass** [comment]
error:Cannot invoke delegate (invalid arguments for AddMenultemB)
![Uploading 2.png…]()
![Uploading 3.png…]()

**Comment by INotGreen** [comment]
OK, there is indeed this bug. I have fixed it in main.lua.  Update plugns again.
