### ISSUE TITLE
最新版本反向代理失败

### ISSUE THREAD

**Issue by yuebusao** [INotGreen/XiebroC2#37]
目标环境：ubuntu1604
teamserver：ubuntu
添加反向代理
<img width="227" alt="1730964962865" src="https://github.com/user-attachments/assets/a0178811-9b33-4fca-a9b7-7e7e67f08ced">
teamserver报错：
<img width="396" alt="1730964983940" src="https://github.com/user-attachments/assets/e9324686-19ed-41cc-87ad-be18455981f9">

**Comment by INotGreen** [comment]
没看懂第二个截图

**Comment by yuebusao** [comment]
> 没看懂第二个截图，你需要在服务端开启这两个端口，一个用作 tcp反向隧道，一个用作 Socks5 服务，可以用IPtables，或者开放防火墙的端口放行策略

感谢回复，这是TeamServer的日志报错信息。我的防火墙是关闭的并且这两个端口都没有占用。

**Comment by INotGreen** [comment]
<img width="1587" alt="image" src="https://github.com/user-attachments/assets/b01292a0-67f2-4066-9ffc-caac161c3516">
我经过测试，反向代理没有问题
