### ISSUE TITLE
【BUG】文件操作功能异常

### ISSUE THREAD

**Issue by badboycxcc** [INotGreen/XiebroC2#6]
![image](https://github.com/INotGreen/XiebroC2/assets/72059221/82b5719d-bd24-4451-9a63-4c10605239c4)

![image](https://github.com/INotGreen/XiebroC2/assets/72059221/b8d4def9-b837-4318-87da-fd205affc90c)

**Comment by INotGreen** [comment]
好的，感谢反馈，这个bug我后面会解决

**Comment by badboycxcc** [comment]
包括文件删除、重命名功能

**Comment by badboycxcc** [comment]
https://github.com/INotGreen/XiebroC2/assets/72059221/0dd648a7-1dba-49b3-96a5-3c65f3595e67

**Comment by INotGreen** [comment]
已经修复以上bug
