### ISSUE TITLE
【BUG】重新打开控制台后无法获取之前监听信息

### ISSUE THREAD

**Issue by badboycxcc** [INotGreen/XiebroC2#8]
设置好监听后关闭控制台，Teamserver 还在运行，重新打开控制台无法显示直接配置好的监听与上线主机，并且配置文件是有监听的配置的。

![image](https://github.com/INotGreen/XiebroC2/assets/72059221/0d8e6589-0fd9-4e69-b548-210f6e8f9660)

![image](https://github.com/INotGreen/XiebroC2/assets/72059221/6a9d2178-444e-43a4-848c-52caaab1bbe6)

**Comment by badboycxcc** [comment]
这是和用户名绑定的？切换原来用户名登录即可看见。不知道是BUG还是这样设置

**Comment by INotGreen** [comment]
监听器的Host需要和你TeamserverIP设成一样

**Comment by badboycxcc** [comment]
> 监听器的Host需要和你TeamserverIP设成一样

是一样的，好像是个BUG，刚刚发现不同用户名登录又可以显示了

**Comment by badboycxcc** [comment]
在这个错误后就可以了
![image](https://github.com/INotGreen/XiebroC2/assets/72059221/63b266ea-641f-4a7b-9e36-c4c102d25b38)
```
Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
```

**Comment by INotGreen** [comment]
最好不要关闭控制台
