### ISSUE TITLE
【BUG】powershell 命令执行失败

### ISSUE THREAD

**Issue by badboycxcc** [INotGreen/XiebroC2#9]
![image](https://github.com/INotGreen/XiebroC2/assets/72059221/d4574471-3a28-48c9-a617-d4cc32041f2f)

**Comment by badboycxcc** [comment]
nps 倒是能正常使用

**Comment by badboycxcc** [comment]
进程管理中 Kill 功能不能使用，会话为管理员权限，杀死进程为notepad （记事本）

**Comment by badboycxcc** [comment]
> 进程管理中 Kill 功能不能使用，会话为管理员权限，杀死进程为notepad （记事本）

进程管理刷新功能不能正常使用

**Comment by INotGreen** [comment]
powershell的进程比较铭感所以就用nps代替了

**Comment by INotGreen** [comment]
进程刷新是可以刷新的，不过有延迟

**Comment by INotGreen** [comment]
已经修复以上bug
